### ISSUE TITLE
Broken images on JavaScript-From-Workers-to-Shared-Memory

### ISSUE THREAD

**Issue by HenriqueLimas** [lucasfcosta/blog#15]
Some images on the "JavaScript From Workers to Shared Memory" are broken:

- https://github.com/lucasfcosta/lucasfcosta.github.io/raw/master/assets/eventloop.png
- https://github.com/lucasfcosta/lucasfcosta.github.io/raw/master/shared-memory-typed-array.png

Btw, nice post, and thanks!

**Comment by lucasfcosta** [comment]
@HenriqueLimas Thanks! I'll fix this by the afternoon :)

**Comment by lucasfcosta** [comment]
Just fixed this, thanks again for your help, @HenriqueLimas 😄
