### ISSUE TITLE
typo in gentle lambda part 1 post?

### ISSUE THREAD

**Issue by daveloyall** [lucasfcosta/blog#26]
> [The `ID` is an abstraction is called the metavariable...](https://github.com/lucasfcosta/lucasfcosta.github.io/blame/5d07e2491f05b3b0bfe4bc43ab2a3a116a44f7c0/_posts/2018-07-29-An-Introduction-to-Lambda-Calculus-Part-1.md#L55)

To my eye, there are too many 'is' there.  Help!

**Comment by lucasfcosta** [comment]
LOL I've just fixed it! Thanks @daveloyall
