### ISSUE TITLE
Reddit share icon's title references to G+ (RIP)

### ISSUE THREAD

**Issue by DanFitzgibbon** [lucasfcosta/blog#42]
After reading the [excellent post](https://github.com/lucasfcosta/lucasfcosta.github.io/blob/36b4365c3d028cae3dc36cc9008e1fddfd11561f/_posts/2021-09-30-explaining-in-writing.md) on explanatory writing, browsed around and, while mindlessly hovering with the trackpad, noticed the reddit share icon referenced Google+ (RIP): https://github.com/lucasfcosta/lucasfcosta.github.io/blob/36b4365c3d028cae3dc36cc9008e1fddfd11561f/_layouts/post.html#L27

PS: Kudos on the content and your voice, btw!

**Comment by lucasfcosta** [comment]
Thank you @DanFitzgibbon! It took me a while, but I fixed it :D
