### ISSUE TITLE
Minor typo in Explaining in Writing

### ISSUE THREAD

**Issue by DanFitzgibbon** [lucasfcosta/blog#43]
This is probably my grammatical OCD talking out loud but attention span is an amount of time so in:

https://github.com/lucasfcosta/lucasfcosta.github.io/blob/36b4365c3d028cae3dc36cc9008e1fddfd11561f/_posts/2021-09-30-explaining-in-writing.md#L92

slower could be replaced by **lower**, I think.

**Comment by lucasfcosta** [comment]
Thanks Dan! Fixed :D
